[package]
name = "ptoken-repro-stack-buffer-parse"
version = "0.1.0"
edition = "2021"
publish = false

[target.'cfg(target_arch = "bpf")'.dependencies]
solana-compiler-builtins = { git = "https://github.com/blueshift-gg/solana-compiler-builtins", branch = "main" }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"

[lints.rust]
explicit_builtin_cfgs_in_flags = "allow"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_feature, values("static-syscalls"))'] }

[workspace]
