[unstable]
build-std = ["core", "alloc"]

[target.bpfel-unknown-none]
rustflags = [
    "-C", "linker=sbpf-linker", 
    "-C", "panic=abort", 
    "-C", "relocation-model=static", 
    "-C", "link-arg=--export=__multi3", 
    "-C", "link-arg=--arch=v3", "-C", "link-arg=--llvm-args=--bpf-max-stores-per-memfunc=5", 
    "-C", "link-arg=--llvm-args=--disable-gotox", 
    "-C", "link-arg=--override-cpu-flag=v3", 
    "-C", "link-arg=--llvm-args=--bpf-allows-libcalls"
]
